In [1]:
from distgen import Generator
from gpt import GPT

%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'

In [20]:
YAML="""
n_particle: 200000
output:
  type: null
px_dist:
  sigma_px: 0.1 keV/c
  type: gaussian
py_dist:
  sigma_py: 0.1 keV/c
  type: gaussian
pz_dist:
  avg_pz: 15 keV/c
  sigma_pz: 0.1 keV/c
  type: gaussian
r_dist:
  sigma_xy:
    units: millimeter
    value: 1.0
  type: radial_gaussian
random:
  type: hammersley
species: electron
spin_polarization: 0.35
start:
  tstart:
    units: second
    value: 0
  type: time
total_charge:
  units: picocoulomb
  value: 10
transforms: null
z_dist:
  avg_z:
    units: millimeter
    value: 0.0
  sigma_z:
    units: millimeter
    value: 2.0
  type: gaussian
"""

In [21]:
D = Generator(YAML)

In [22]:
D['n_particle']=1_000

In [23]:
B = D.beam()

In [24]:
from distgen.writers import write_gpt

In [25]:
write_gpt(B, 'gpt_particles.gdf', verbose=1, asci2gdf_bin='$ASCI2GDF_BIN')

Printing 1000 particles to "gpt_particles.gdf":    Converting file to GDF: done. Time ellapsed: 16.165 ms.
...done. Time ellapsed: 32.3739 ms.


In [26]:
from gpt.template import BASIC_TEMPLATE

#BASIC_TEMPLATE

In [27]:
with open('gpt.in', 'w') as fid:
    fid.write('\n'.join(BASIC_TEMPLATE))

In [28]:
G = GPT('gpt.in', spin_tracking=True, verbose=True)
G.set_variables({'Ntout': 100, 'tmax': 5e-8, 'ZSTOP':1.0})
G.run()

GPT.configure_gpt:
   Original input file "gpt.in" in "/Users/colwyngulliford/GitHub/lume-gpt/examples"
   Configured to run in "/var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmp6viw1512"
GPT.run_gpt:
   Running GPT...
   Writing gpt input file to "/var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmp6viw1512/gpt.in"
   Running with timeout = None sec.
   Loading GPT data from /var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmp6viw1512/gpt.out.gdf
   GDF data loaded, time ellapsed: 0.0235183 (sec).
   Converting tout and screen data to ParticleGroup(s)
   Run finished, total time ellapsed: 0.150009 (sec)


In [29]:
G.n_screen, G.n_tout

(0, 100)

In [30]:
G.tout[0]['sz']

array([-0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57735027,
       -0.57735027, -0.57735027, -0.57735027, -0.57735027, -0.57

In [19]:
G.tout[0]['mean_sx'], G.tout[0]['mean_sy'], G.tout[0]['mean_sz']

(np.float64(-2.3089815049394293e-14),
 np.float64(5.726246131663433e-15),
 np.float64(2.02072594216369e-12))

In [32]:
B.avg('x')

<Quantity(3.09167026e-20, 'meter')>

In [35]:
B.avg('sx'), B.avg('sy'), B.avg('sz')

(<Quantity(-0.39458226, 'nanometer * electron_volt / speed_of_light')>,
 <Quantity(0.097855922, 'nanometer * electron_volt / speed_of_light')>,
 <Quantity(34.5322216, 'nanometer * electron_volt / speed_of_light')>)

In [36]:
G.tout[0]['sx']**2 + G.tout[0]['sy']**2 + G.tout[0]['sz']**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [37]:
B.sz

<Quantity([-98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98

In [39]:
import numpy as np

np.sum(B.sz)/np.sum(np.abs(B.sz))

<Quantity(0.35, 'dimensionless')>

In [40]:
B.sz

<Quantity([-98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98.66349017 -98.66349017 -98.66349017
 -98.66349017 -98.66349017 -98

In [42]:
np.unique(B.sz.magnitude)

array([-98.66349017,  98.66349017])