In [1]:
from distgen import Generator
from gpt import GPT

%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'

In [2]:
YAML="""
n_particle: 200000
output:
  type: null
px_dist:
  sigma_px: 0.1 keV/c
  type: gaussian
py_dist:
  sigma_py: 0.1 keV/c
  type: gaussian
pz_dist:
  avg_pz: 15 keV/c
  sigma_pz: 0.1 keV/c
  type: gaussian
r_dist:
  sigma_xy:
    units: millimeter
    value: 1.0
  type: radial_gaussian
random:
  type: hammersley
species: electron
spin_polarization: 0.35
start:
  tstart:
    units: second
    value: 0
  type: time
total_charge:
  units: picocoulomb
  value: 10
transforms: null
z_dist:
  avg_z:
    units: millimeter
    value: 0.0
  sigma_z:
    units: millimeter
    value: 2.0
  type: gaussian
"""

In [3]:
D = Generator(YAML)

In [4]:
D['n_particle']=1_000

In [5]:
B = D.beam()

In [6]:
from distgen.writers import write_gpt

In [7]:
write_gpt(B, 'gpt_particles.gdf', verbose=1, asci2gdf_bin='$ASCI2GDF_BIN')

Printing 1000 particles to "gpt_particles.gdf":    Converting file to GDF: done. Time ellapsed: 24.492 ms.
...done. Time ellapsed: 37.6701 ms.


In [8]:
from gpt.template import BASIC_TEMPLATE

#BASIC_TEMPLATE

In [9]:
with open('gpt.in', 'w') as fid:
    fid.write('\n'.join(BASIC_TEMPLATE))

In [10]:
G = GPT('gpt.in', spin_tracking=True, verbose=True)
G.set_variables({'Ntout': 100, 'tmax': 5e-8, 'ZSTOP':1.0})
G.run()

GPT.configure_gpt:
   Original input file "gpt.in" in "/Users/colwyngulliford/GitHub/lume-gpt/examples"
   Configured to run in "/var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmpvf_3f7sg"
GPT.run_gpt:
   Running GPT...
   Writing gpt input file to "/var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmpvf_3f7sg/gpt.in"
   Running with timeout = None sec.
   Loading GPT data from /var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmpvf_3f7sg/gpt.out.gdf
   GDF data loaded, time ellapsed: 0.0451248 (sec).
   Converting tout and screen data to ParticleGroup(s)
   Run finished, total time ellapsed: 0.248132 (sec)


In [11]:
G.n_screen, G.n_tout

(0, 100)

In [12]:
G.tout_spin[0]['sz'].mean()

np.float64(0.35)

In [13]:
G.tout_stat('mean_sz')

array([0.35      , 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879032,
       0.34879032, 0.34879032, 0.34879032, 0.34879032, 0.34879

In [14]:
B.avg('x')

<Quantity(-1.41878019e-20, 'meter')>

In [15]:
B.avg('sx'), B.avg('sy'), B.avg('sz')

(<Quantity(0.0, 'nanometer * electron_volt / speed_of_light')>,
 <Quantity(0.0, 'nanometer * electron_volt / speed_of_light')>,
 <Quantity(34.5322216, 'nanometer * electron_volt / speed_of_light')>)

In [16]:
G.tout_spin[0]['sx']**2 + G.tout_spin[0]['sy']**2 + G.tout_spin[0]['sz']**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [17]:
#B.sz

In [18]:
import numpy as np

np.sum(B.sz)/np.sum(np.abs(B.sz))

<Quantity(0.35, 'dimensionless')>

In [19]:
theta = 0
thr = np.pi * theta / 180

ehat = np.array([np.cos(thr), 0, np.sin(thr)])

ehat = ehat / np.sqrt(np.sum(ehat**2))

np.sqrt(np.sum(ehat**2))

np.float64(1.0)

In [20]:
#np.sum(B.sx * ehat[0])/np.sum(np.abs(B.sx * ehat[0]))

In [21]:
#np.sum(B.sz * ehat[1])/np.sum(np.abs(B.sz* ehat[1]))

In [22]:
#np.sum(B.sz * ehat[2])/np.sum(np.abs(B.sz* ehat[2]))

In [23]:
ehat

array([1., 0., 0.])

In [24]:
np.sum(B.w * B.sz/np.sqrt(B.s2))

<Quantity(0.35, 'dimensionless')>

In [25]:
sx0 = np.sum(B.w * B.sx)/np.sqrt(B.s2)
sy0 = np.sum(B.w * B.sy)/np.sqrt(B.s2)
sz0 = np.sum(B.w * B.sz)/np.sqrt(B.s2)

In [26]:
max(sx0)

<Quantity(0.0, 'dimensionless')>

In [27]:
max(sy0)

<Quantity(0.0, 'dimensionless')>

In [28]:
max(sz0)

<Quantity(0.35, 'dimensionless')>

In [29]:
P = np.array([ np.sum(B.w * B.sx/ np.sqrt(B.s2)), np.sum(B.w * B.sy/np.sqrt(B.s2)), np.sum(B.w * B.sz/np.sqrt(B.s2)) ])

In [30]:
P

array([0.  , 0.  , 0.35])

In [31]:
P = np.array([ B.sx[0]/np.sqrt(B.s2)[0],  B.sy[0]/np.sqrt(B.s2)[0], B.sz[0]/np.sqrt(B.s2)[0]])

In [32]:
np.sum(P**2)

np.float64(1.0)

In [35]:
import os

os.remove('gpt.in')
os.remove('gpt_particles.gdf')

In [34]:
#G.tout_spin[0]['sx']