In [1]:
from distgen import Generator
from gpt import GPT

%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'

In [2]:
YAML="""
n_particle: 200000
output:
  type: null
px_dist:
  sigma_px: 0.1 keV/c
  type: gaussian
py_dist:
  sigma_py: 0.1 keV/c
  type: gaussian
pz_dist:
  avg_pz: 15 keV/c
  sigma_pz: 0.1 keV/c
  type: gaussian
r_dist:
  sigma_xy:
    units: millimeter
    value: 1.0
  type: radial_gaussian
random:
  type: hammersley
species: electron
spin_polarization: 0.35
start:
  tstart:
    units: second
    value: 0
  type: time
total_charge:
  units: picocoulomb
  value: 10
transforms: null
z_dist:
  avg_z:
    units: millimeter
    value: 0.0
  sigma_z:
    units: millimeter
    value: 2.0
  type: gaussian
"""

In [3]:
D = Generator(YAML)

In [4]:
D['n_particle']=1_000

In [5]:
B = D.beam()

In [6]:
from distgen.writers import write_gpt

In [7]:
write_gpt(B, 'gpt_particles.gdf', verbose=1, asci2gdf_bin='$ASCI2GDF_BIN')

Printing 1000 particles to "gpt_particles.gdf":    Converting file to GDF: done. Time ellapsed: 11.9321 ms.
...done. Time ellapsed: 20.5419 ms.


In [8]:
from gpt.template import BASIC_TEMPLATE

#BASIC_TEMPLATE

In [9]:
with open('gpt.in', 'w') as fid:
    fid.write('\n'.join(BASIC_TEMPLATE))

In [10]:
G = GPT('gpt.in', spin_tracking=True, verbose=True)
G.set_variables({'Ntout': 100, 'tmax': 5e-8, 'ZSTOP':1.0})
G.run()

GPT.configure_gpt:
   Original input file "gpt.in" in "/Users/colwyngulliford/GitHub/lume-gpt/examples"
   Configured to run in "/var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmp9d61ynln"
GPT.run_gpt:
   Running GPT...
   Writing gpt input file to "/var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmp9d61ynln/gpt.in"
   Running with timeout = None sec.
   Loading GPT data from /var/folders/w8/8n1md1352pzd3nqp0lhc5jy00000gn/T/tmp9d61ynln/gpt.out.gdf
   GDF data loaded, time ellapsed: 0.0215669 (sec).
   Converting tout and screen data to ParticleGroup(s)
   Run finished, total time ellapsed: 0.133416 (sec)


In [11]:
G.n_screen, G.n_tout

(0, 100)

In [12]:
G.tout_spin[0]['sz'].mean()

np.float64(0.2020725942163691)

In [13]:
G.tout_stat('mean_sz')

array([0.20207259, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137419,
       0.20137419, 0.20137419, 0.20137419, 0.20137419, 0.20137

In [14]:
B.avg('x')

<Quantity(3.09167026e-20, 'meter')>

In [15]:
B.avg('sx'), B.avg('sy'), B.avg('sz')

(<Quantity(-0.39458226, 'nanometer * electron_volt / speed_of_light')>,
 <Quantity(0.097855922, 'nanometer * electron_volt / speed_of_light')>,
 <Quantity(34.5322216, 'nanometer * electron_volt / speed_of_light')>)

In [16]:
G.tout_spin[0]['sx']**2 + G.tout_spin[0]['sy']**2 + G.tout_spin[0]['sz']**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [17]:
#B.sz

In [18]:
import numpy as np

np.sum(B.sz)/np.sum(np.abs(B.sz))

<Quantity(0.35, 'dimensionless')>

In [37]:
theta = 0
thr = np.pi * theta / 180

ehat = np.array([np.cos(thr), 0, np.sin(thr)])

ehat = ehat / np.sqrt(np.sum(ehat**2))

np.sqrt(np.sum(ehat**2))

np.float64(1.0)

In [38]:
np.sum(B.sx * ehat[0])/np.sum(np.abs(B.sx * ehat[0]))

<Quantity(-0.00444854548, 'dimensionless')>

In [39]:
np.sum(B.sz * ehat[1])/np.sum(np.abs(B.sz* ehat[1]))

<Quantity(nan, 'dimensionless')>

In [40]:
np.sum(B.sz * ehat[2])/np.sum(np.abs(B.sz* ehat[2]))

<Quantity(nan, 'dimensionless')>

In [41]:
ehat

array([1., 0., 0.])

In [48]:
np.sum(B.w * B.sz/np.sqrt(B.s2))

<Quantity(0.202072594, 'dimensionless')>

In [55]:
sx0 = np.sum(B.w * B.sx)/np.sqrt(B.s2)
sy0 = np.sum(B.w * B.sy)/np.sqrt(B.s2)
sz0 = np.sum(B.w * B.sz)/np.sqrt(B.s2)

In [57]:
max(sx0)

<Quantity(-0.0023089815, 'dimensionless')>

In [58]:
max(sy0)

<Quantity(0.000572624613, 'dimensionless')>

In [59]:
max(sz0)

<Quantity(0.202072594, 'dimensionless')>

In [68]:
P = np.array([ np.sum(B.w * B.sx/ np.sqrt(B.s2)), np.sum(B.w * B.sy/np.sqrt(B.s2)), np.sum(B.w * B.sz/np.sqrt(B.s2)) ])

In [69]:
P

array([-0.00230898,  0.00057262,  0.20207259])

In [78]:
P = np.array([ B.sx[0]/np.sqrt(B.s2)[0],  B.sy[0]/np.sqrt(B.s2)[0], B.sz[0]/np.sqrt(B.s2)[0]])

In [79]:
np.sum(P**2)

np.float64(1.0)

In [80]:
import os

os.remove('gpt.in')
os.remove('gpt_particles.gdf')